---
# tasks file for mysql    
    - name: Install MySQL Database
      apt: name="{{ item }}" state=present
      with_items:
        - mysql-server
        - mysql-client

    - name: Start Database Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create database users
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        host: '%'
        state: present
