---
# tasks file for mysql    
    - name: Install MySQL Database
      apt:
        name: ['mysql-server','mysql-client'] 
        state: present
        force: yes
        update_cache: yes

    - name: Start Database Service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create database users
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        host: '%'
        state: present
